using System;
using System.Collections.Generic;

namespace RentkuttCRM.Services
{
    public static class NorskeKommuner
    {
        public static readonly string[] Fylker = new[]
        {
            "Oslo",
            "Akershus",
            "Østfold",
            "Buskerud",
            "Innlandet",
            "Vestfold",
            "Telemark",
            "Agder",
            "Rogaland",
            "Vestland",
            "Møre og Romsdal",
            "Trøndelag",
            "Nordland",
            "Troms",
            "Finnmark"
        };

        public static readonly Dictionary<string, string> KommuneTilFylke = new(StringComparer.OrdinalIgnoreCase)
        {
            // Oslo
            { "Oslo", "Oslo" },

            // Akershus
            { "Bærum", "Akershus" },
            { "Asker", "Akershus" },
            { "Lillestrøm", "Akershus" },
            { "Nordre Follo", "Akershus" },
            { "Ullensaker", "Akershus" },
            { "Lørenskog", "Akershus" },
            { "Nesodden", "Akershus" },
            { "Frogn", "Akershus" },
            { "Vestby", "Akershus" },
            { "Ås", "Akershus" },
            { "Enebakk", "Akershus" },
            { "Aurskog-Høland", "Akershus" },
            { "Rælingen", "Akershus" },
            { "Nittedal", "Akershus" },
            { "Gjerdrum", "Akershus" },
            { "Nannestad", "Akershus" },
            { "Eidsvoll", "Akershus" },
            { "Hurdal", "Akershus" },
            { "Nes", "Akershus" },
            { "Lunner", "Akershus" },
            { "Jevnaker", "Akershus" },

            // Østfold
            { "Fredrikstad", "Østfold" },
            { "Sarpsborg", "Østfold" },
            { "Moss", "Østfold" },
            { "Halden", "Østfold" },
            { "Indre Østfold", "Østfold" },
            { "Rakkestad", "Østfold" },
            { "Råde", "Østfold" },
            { "Våler (Østfold)", "Østfold" },
            { "Hvaler", "Østfold" },
            { "Skiptvet", "Østfold" },
            { "Marker", "Østfold" },
            { "Aremark", "Østfold" },

            // Buskerud
            { "Drammen", "Buskerud" },
            { "Kongsberg", "Buskerud" },
            { "Ringerike", "Buskerud" },
            { "Lier", "Buskerud" },
            { "Øvre Eiker", "Buskerud" },
            { "Nedre Eiker", "Buskerud" },
            { "Modum", "Buskerud" },
            { "Hole", "Buskerud" },
            { "Flesberg", "Buskerud" },
            { "Rollag", "Buskerud" },
            { "Nore og Uvdal", "Buskerud" },
            { "Sigdal", "Buskerud" },
            { "Krødsherad", "Buskerud" },
            { "Flå", "Buskerud" },
            { "Nesbyen", "Buskerud" },
            { "Gol", "Buskerud" },
            { "Hemsedal", "Buskerud" },
            { "Ål", "Buskerud" },
            { "Hol", "Buskerud" },

            // Innlandet
            { "Hamar", "Innlandet" },
            { "Lillehammer", "Innlandet" },
            { "Gjøvik", "Innlandet" },
            { "Ringsaker", "Innlandet" },
            { "Elverum", "Innlandet" },
            { "Stange", "Innlandet" },
            { "Løten", "Innlandet" },
            { "Nord-Odal", "Innlandet" },
            { "Sør-Odal", "Innlandet" },
            { "Kongsvinger", "Innlandet" },
            { "Eidskog", "Innlandet" },
            { "Grue", "Innlandet" },
            { "Åsnes", "Innlandet" },
            { "Våler (Innlandet)", "Innlandet" },
            { "Trysil", "Innlandet" },
            { "Åmot", "Innlandet" },
            { "Stor-Elvdal", "Innlandet" },
            { "Rendalen", "Innlandet" },
            { "Engerdal", "Innlandet" },
            { "Tolga", "Innlandet" },
            { "Tynset", "Innlandet" },
            { "Alvdal", "Innlandet" },
            { "Folldal", "Innlandet" },
            { "Os (Innlandet)", "Innlandet" },
            { "Dovre", "Innlandet" },
            { "Lesja", "Innlandet" },
            { "Skjåk", "Innlandet" },
            { "Lom", "Innlandet" },
            { "Vågå", "Innlandet" },
            { "Nord-Fron", "Innlandet" },
            { "Sel", "Innlandet" },
            { "Sør-Fron", "Innlandet" },
            { "Ringebu", "Innlandet" },
            { "Øyer", "Innlandet" },
            { "Gausdal", "Innlandet" },
            { "Østre Toten", "Innlandet" },
            { "Vestre Toten", "Innlandet" },
            { "Gran", "Innlandet" },
            { "Søndre Land", "Innlandet" },
            { "Nordre Land", "Innlandet" },
            { "Sør-Aurdal", "Innlandet" },
            { "Etnedal", "Innlandet" },
            { "Nord-Aurdal", "Innlandet" },
            { "Vestre Slidre", "Innlandet" },
            { "Øystre Slidre", "Innlandet" },
            { "Vang", "Innlandet" },

            // Vestfold
            { "Tønsberg", "Vestfold" },
            { "Sandefjord", "Vestfold" },
            { "Larvik", "Vestfold" },
            { "Horten", "Vestfold" },
            { "Holmestrand", "Vestfold" },
            { "Færder", "Vestfold" },

            // Telemark
            { "Skien", "Telemark" },
            { "Porsgrunn", "Telemark" },
            { "Notodden", "Telemark" },
            { "Bamble", "Telemark" },
            { "Kragerø", "Telemark" },
            { "Siljan", "Telemark" },
            { "Nome", "Telemark" },
            { "Midt-Telemark", "Telemark" },
            { "Tinn", "Telemark" },
            { "Hjartdal", "Telemark" },
            { "Seljord", "Telemark" },
            { "Kviteseid", "Telemark" },
            { "Nissedal", "Telemark" },
            { "Fyresdal", "Telemark" },
            { "Tokke", "Telemark" },
            { "Vinje", "Telemark" },
            { "Drangedal", "Telemark" },

            // Agder
            { "Kristiansand", "Agder" },
            { "Arendal", "Agder" },
            { "Grimstad", "Agder" },
            { "Vennesla", "Agder" },
            { "Lillesand", "Agder" },
            { "Froland", "Agder" },
            { "Lindesnes", "Agder" },
            { "Farsund", "Agder" },
            { "Flekkefjord", "Agder" },
            { "Tvedestrand", "Agder" },
            { "Risør", "Agder" },
            { "Gjerstad", "Agder" },
            { "Vegårshei", "Agder" },
            { "Åmli", "Agder" },
            { "Iveland", "Agder" },
            { "Evje og Hornnes", "Agder" },
            { "Bygland", "Agder" },
            { "Valle", "Agder" },
            { "Bykle", "Agder" },
            { "Birkenes", "Agder" },
            { "Kvinesdal", "Agder" },
            { "Hægebostad", "Agder" },
            { "Lyngdal", "Agder" },
            { "Åseral", "Agder" },
            { "Sirdal", "Agder" },

            // Rogaland
            { "Stavanger", "Rogaland" },
            { "Sandnes", "Rogaland" },
            { "Haugesund", "Rogaland" },
            { "Sola", "Rogaland" },
            { "Karmøy", "Rogaland" },
            { "Klepp", "Rogaland" },
            { "Time", "Rogaland" },
            { "Hå", "Rogaland" },
            { "Gjesdal", "Rogaland" },
            { "Randaberg", "Rogaland" },
            { "Strand", "Rogaland" },
            { "Hjelmeland", "Rogaland" },
            { "Suldal", "Rogaland" },
            { "Sauda", "Rogaland" },
            { "Tysvær", "Rogaland" },
            { "Vindafjord", "Rogaland" },
            { "Bokn", "Rogaland" },
            { "Utsira", "Rogaland" },
            { "Kvitsøy", "Rogaland" },
            { "Bjerkreim", "Rogaland" },
            { "Eigersund", "Rogaland" },
            { "Lund", "Rogaland" },
            { "Sokndal", "Rogaland" },

            // Vestland
            { "Bergen", "Vestland" },
            { "Askøy", "Vestland" },
            { "Øygarden", "Vestland" },
            { "Alver", "Vestland" },
            { "Bjørnafjorden", "Vestland" },
            { "Voss", "Vestland" },
            { "Stord", "Vestland" },
            { "Kvinnherad", "Vestland" },
            { "Ullensvang", "Vestland" },
            { "Sunnfjord", "Vestland" },
            { "Kinn", "Vestland" },
            { "Sogndal", "Vestland" },
            { "Osterøy", "Vestland" },
            { "Vaksdal", "Vestland" },
            { "Modalen", "Vestland" },
            { "Austrheim", "Vestland" },
            { "Fedje", "Vestland" },
            { "Masfjorden", "Vestland" },
            { "Gulen", "Vestland" },
            { "Solund", "Vestland" },
            { "Hyllestad", "Vestland" },
            { "Høyanger", "Vestland" },
            { "Vik", "Vestland" },
            { "Aurland", "Vestland" },
            { "Lærdal", "Vestland" },
            { "Årdal", "Vestland" },
            { "Luster", "Vestland" },
            { "Askvoll", "Vestland" },
            { "Fjaler", "Vestland" },
            { "Bremanger", "Vestland" },
            { "Stad", "Vestland" },
            { "Gloppen", "Vestland" },
            { "Stryn", "Vestland" },
            { "Samnanger", "Vestland" },
            { "Austevoll", "Vestland" },
            { "Fitjar", "Vestland" },
            { "Tysnes", "Vestland" },
            { "Kvam", "Vestland" },
            { "Etne", "Vestland" },
            { "Sveio", "Vestland" },
            { "Bømlo", "Vestland" },
            { "Eidfjord", "Vestland" },
            { "Ulvik", "Vestland" },

            // Møre og Romsdal
            { "Ålesund", "Møre og Romsdal" },
            { "Molde", "Møre og Romsdal" },
            { "Kristiansund", "Møre og Romsdal" },
            { "Ørsta", "Møre og Romsdal" },
            { "Volda", "Møre og Romsdal" },
            { "Herøy (Møre og Romsdal)", "Møre og Romsdal" },
            { "Ulstein", "Møre og Romsdal" },
            { "Hareid", "Møre og Romsdal" },
            { "Sula", "Møre og Romsdal" },
            { "Giske", "Møre og Romsdal" },
            { "Sykkylven", "Møre og Romsdal" },
            { "Stranda", "Møre og Romsdal" },
            { "Fjord", "Møre og Romsdal" },
            { "Vestnes", "Møre og Romsdal" },
            { "Rauma", "Møre og Romsdal" },
            { "Aukra", "Møre og Romsdal" },
            { "Averøy", "Møre og Romsdal" },
            { "Gjemnes", "Møre og Romsdal" },
            { "Tingvoll", "Møre og Romsdal" },
            { "Sunndal", "Møre og Romsdal" },
            { "Surnadal", "Møre og Romsdal" },
            { "Smøla", "Møre og Romsdal" },
            { "Aure", "Møre og Romsdal" },
            { "Hustadvika", "Møre og Romsdal" },
            { "Sande (Møre og Romsdal)", "Møre og Romsdal" },
            { "Vanylven", "Møre og Romsdal" },

            // Trøndelag
            { "Trondheim", "Trøndelag" },
            { "Steinkjer", "Trøndelag" },
            { "Stjørdal", "Trøndelag" },
            { "Levanger", "Trøndelag" },
            { "Verdal", "Trøndelag" },
            { "Melhus", "Trøndelag" },
            { "Malvik", "Trøndelag" },
            { "Orkland", "Trøndelag" },
            { "Namsos", "Trøndelag" },
            { "Nærøysund", "Trøndelag" },
            { "Skaun", "Trøndelag" },
            { "Selbu", "Trøndelag" },
            { "Tydal", "Trøndelag" },
            { "Meråker", "Trøndelag" },
            { "Frosta", "Trøndelag" },
            { "Inderøy", "Trøndelag" },
            { "Snåsa", "Trøndelag" },
            { "Lierne", "Trøndelag" },
            { "Røyrvik", "Trøndelag" },
            { "Namsskogan", "Trøndelag" },
            { "Grong", "Trøndelag" },
            { "Høylandet", "Trøndelag" },
            { "Overhalla", "Trøndelag" },
            { "Flatanger", "Trøndelag" },
            { "Osen", "Trøndelag" },
            { "Åfjord", "Trøndelag" },
            { "Ørland", "Trøndelag" },
            { "Indre Fosen", "Trøndelag" },
            { "Heim", "Trøndelag" },
            { "Hitra", "Trøndelag" },
            { "Frøya", "Trøndelag" },
            { "Rindal", "Trøndelag" },
            { "Midtre Gauldal", "Trøndelag" },
            { "Oppdal", "Trøndelag" },
            { "Rennebu", "Trøndelag" },
            { "Røros", "Trøndelag" },
            { "Holtålen", "Trøndelag" },

            // Nordland
            { "Bodø", "Nordland" },
            { "Rana", "Nordland" },
            { "Narvik", "Nordland" },
            { "Vefsn", "Nordland" },
            { "Alstahaug", "Nordland" },
            { "Brønnøy", "Nordland" },
            { "Sortland", "Nordland" },
            { "Vestvågøy", "Nordland" },
            { "Fauske", "Nordland" },
            { "Vågan", "Nordland" },
            { "Meløy", "Nordland" },
            { "Hadsel", "Nordland" },
            { "Øksnes", "Nordland" },
            { "Sømna", "Nordland" },
            { "Bindal", "Nordland" },
            { "Grane", "Nordland" },
            { "Hattfjelldal", "Nordland" },
            { "Vevelstad", "Nordland" },
            { "Herøy (Nordland)", "Nordland" },
            { "Leirfjord", "Nordland" },
            { "Dønna", "Nordland" },
            { "Nesna", "Nordland" },
            { "Hemnes", "Nordland" },
            { "Lurøy", "Nordland" },
            { "Træna", "Nordland" },
            { "Rødøy", "Nordland" },
            { "Gildeskål", "Nordland" },
            { "Beiarn", "Nordland" },
            { "Saltdal", "Nordland" },
            { "Sørfold", "Nordland" },
            { "Steigen", "Nordland" },
            { "Hamarøy", "Nordland" },
            { "Lødingen", "Nordland" },
            { "Evenes", "Nordland" },
            { "Bø (Nordland)", "Nordland" },
            { "Andøy", "Nordland" },
            { "Moskenes", "Nordland" },
            { "Flakstad", "Nordland" },
            { "Værøy", "Nordland" },
            { "Røst", "Nordland" },

            // Troms
            { "Tromsø", "Troms" },
            { "Harstad", "Troms" },
            { "Senja", "Troms" },
            { "Målselv", "Troms" },
            { "Balsfjord", "Troms" },
            { "Bardu", "Troms" },
            { "Salangen", "Troms" },
            { "Dyrøy", "Troms" },
            { "Sørreisa", "Troms" },
            { "Gratangen", "Troms" },
            { "Lavangen", "Troms" },
            { "Ibestad", "Troms" },
            { "Kvæfjord", "Troms" },
            { "Skjervøy", "Troms" },
            { "Nordreisa", "Troms" },
            { "Kåfjord", "Troms" },
            { "Storfjord", "Troms" },
            { "Lyngen", "Troms" },
            { "Karlsøy", "Troms" },
            { "Kvænangen", "Troms" },
            { "Tjeldsund", "Troms" },

            // Finnmark
            { "Alta", "Finnmark" },
            { "Sør-Varanger", "Finnmark" },
            { "Hammerfest", "Finnmark" },
            { "Vadsø", "Finnmark" },
            { "Vardø", "Finnmark" },
            { "Nordkapp", "Finnmark" },
            { "Porsanger", "Finnmark" },
            { "Lebesby", "Finnmark" },
            { "Gamvik", "Finnmark" },
            { "Berlevåg", "Finnmark" },
            { "Tana", "Finnmark" },
            { "Nesseby", "Finnmark" },
            { "Båtsfjord", "Finnmark" },
            { "Karasjok", "Finnmark" },
            { "Kautokeino", "Finnmark" },
            { "Loppa", "Finnmark" },
            { "Hasvik", "Finnmark" },
            { "Måsøy", "Finnmark" }
        };

        public static string Fylke(string? kommune)
        {
            if (string.IsNullOrWhiteSpace(kommune))
                return "Ukjent";

            return KommuneTilFylke.TryGetValue(kommune.Trim(), out var fylke)
                ? fylke
                : "Ukjent";
        }
    }
}
